title: Kota Tangerang Selatan
description: Your site description
baseurl: ""  # Leave empty for user/organization pages (username.github.io)
url: "https://dapoerela85.github.io/tangsel"  # Replace with your URL

plugins:
  - jekyll-feed

include:
  - "*.js.liquid"

markdown: kramdown